yhf2000/SDUBAS-backend

controller/projects.py, controller/resources.py, model/db.py, service/Resource.py, service/project.py, type/financial.py, type/project.py
=> 增加了部分API，删除资源资金获取全部的权限检查

controller/projects.py, model/db.py, model/project.py, service/project.py, type/project.py
=> 增加修改部分项目api

const.py, controller/projects.py, model/project.py, service/project.py, type/project.py, utils/auth_permission.py
=> 修改项目内容为线性，完善了项目内容的修改

controller/projects.py, service/project.py
=> 添加了对操作对象的检查

model/permissions.py, type/permissions.py
=> type添加permissions

controller/projects.py, controller/resources.py, model/permissions.py, service/Resource.py, service/permissions.py, service/project.py, type/page.py, type/project.py
增加了查询项目成员，查询学分，查询项目内容得分，对所有api加上了增添操作表，但操作表参数未设置，角色id没对接
=> 增加了几个api，部分对接

controller/projects.py, controller/resources.py, service/Resource.py, service/project.py, type/financial.py, type/project.py
=> 根据操作表的异步操作更新

controller/permissions.py, model/db_init.py, model/permissions.py, service/permissions.py
=> 更新获取用户操作与db初始化

type/permissions.py, type/project.py
=> 增加了对前端数据格式的判断

service/project.py
=> 简化了一个查询函数，修改了几个外连接子查询的错误

controller/projects.py, service/Resource.py, service/project.py
=> 修改了url从项目里获取

controller/projects.py, service/Resource.py, service/project.py
=> 修改了url获取方式

service/project.py
=> 修改了部分函数实现方式

controller/projects.py, model/project.py, service/project.py, type/project.py
缺少部分接口，没完成对content内description的检查，学分缺少培养方案目前时分类返回总学分。
=> 实现了视频完成度的接口，增加了返回项目内容时通过情况，对学分进行了修改

controller/projects.py, service/Resource.py, service/project.py, type/page.py
=> 修改了部分函数调用参数

controller/projects.py, service/project.py, type/project.py
完成返回个人档案项目相关，description完成部分，完成返回学分认定
=> 完成返回个人档案项目相关，description完成部分，完成返回学分认定

controller/projects.py, controller/resources.py, service/project.py
=> 增加了查看某学分项目接口，完善部分接口

controller/projects.py, service/project.py
完成了特殊完成条件的判定，增加了部分模糊查询，增加了几个api对user_id的判断
=> 完成了特殊完成条件的判定，增加了部分模糊查询，增加了几个api对user_id的判断

service/project.py
=> 修改一个group错误

service/project.py
=> 修改了学分认定的bug

controller/projects.py, service/project.py
=> 修改了一个接口的返回格式

controller/projects.py, service/project.py
=> 增加了几个API的功能

controller/projects.py, service/project.py, type/project.py
=> 综合了几个api，修复了查询结果为NONE的报错

controller/projects.py
=> 修改了一些返回值，但是有些接口返回错误的返回值没改

controller/projects.py
=> 修改了封装两次的Bug
